### ISSUE TITLE
[server] 使用者註冊帳號

### ISSUE THREAD

**Issue by chrislin1015** [chrislin1015/JustDoIt#1]
# Task
- [x] http server 取得用戶註冊資料
- [x] 判斷  post 資料是否有資料
- [x] 判斷 email 帳號是否符合格式
- [x] 判斷 password 是否符合規則
- [x] 判斷該 email 帳號是否已經註冊
- [x] 將用戶資料存入 MySQL

# 規則
- Password
  - 密碼必須是英文字母大小寫與數字的組合，不可以是其他字元
  - 必須要有一個英文字母是大寫
  - 必須要有一個英文字母是小寫
  - 必須要有數字

- POST JSON 格式
  - ```
    {
        email: xxxxx@ccc.ccc,
        password: Aabbcc123,
        name: Chris
    }
```
